name: pyagri
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - Cython
    - numpy
    - pandas
    - atomicwrites
    - attrs
    - certifi
    - click
    - click-plugins
    - colorama
    - coverage
    - et-xmlfile
    - iniconfig
    - jdcal
    - munch
    - openpyxl
    - packaging
    - pluggy
    - py
    - pyparsing
    - pytest
    - python-dateutil
    - pytz
    - six
    - toml
    - tqdm
